# Generated by Django 6.0 on 2025-12-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='e.g. Lagos, Kano', max_length=50, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_time', models.CharField(default='3-5 Business Days', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
